### ISSUE TITLE
How to best indicate that there are no error messages being displayed?

### ISSUE THREAD

**Issue by notmessenger** [ember-forge/ember-forge-ui#148]
* https://github.com/ember-forge/ember-forge-ui/blob/form-components/addon/components/form/ef-element-error.js#L24
* https://github.com/ember-forge/ember-forge-ui/blob/form-components/addon/components/form/ef-form-error.js#L25

These components have class name bindings to the `ef-hasContent` class which is applied whenever there is an error message or messages (respectively) being displayed.  The idea here is that when there are no messages being displayed (and this class is not applied) the element can be hidden from display so as to not introduce extraneous spacing in the UI.

While the idea is a correct one the question that is posed is whether the approach is correct or not?  Is there a better way to approach indicating this?  Should a class be applied when there is no message instead of when there is?  That sort of thing.

**Comment by notmessenger** [comment]
I realize now that I will likely want to integrate an "alert" component into the display of the form-level errors so that may provide some direction (or more things to consider).

**Comment by davewasmer** [comment]
Putting on my "hypothetical consumer of forge" hat:

My preference is that the error elements _don't even appear in the DOM_ when there is no error (i.e. a tagless component with a top-level `{{if` block). An acceptable fallback from that is that they have a consistent class name I can target with `display:none` and an "active" class name (when an error is present) I can target to override the `display:none`.

While there's not much functional difference between "hidden except when active" vs "visible except when inactive", the former is the much more common pattern in my experience. So I would _not_ add a class when there are **no** errors, and instead I would add a class when there **are** errors.
