### ISSUE TITLE
List components

### ISSUE THREAD

**Issue by notmessenger** [ember-forge/ember-forge-ui#37]
I have decided to call the components that render `ol` and `ul` elements *lists* rather than *collections*.  Is this acceptable to you?

When doing so do we have two different components - `ef-list-ordered` and `ef-list-unordered` - or do we have single list with an `ordered=true/false` property?  An `ol` element supports three attributes - `reversed`, `start`, and `type` - while the `ul` element supports none.  I'm not sure I'm keen on mixing the ability to set properties against a rendered element to which they don't apply.  What are your thoughts?

**Comment by davewasmer** [comment]
My gut feeling:

I'd prefer `{{ef-list ordered=true}}` over `{{ef-list-ordered}}`. The value of ember-forge I see is in the abstractions it provides. Ordering feels like a property of a list, not a different kind of thing from an unordered list. `{{ef-list-ordered}}` / `{{ef-list-unordered}}` is starting to feel like I'm just writing HTML tags with more words.

> I'm not sure I'm keen on mixing the ability to set properties against a rendered element to which they don't apply. 

I think this will be inevitable with the goals of ember-forge. That said, it could be mitigated by adding some assertions (i.e. throw if you to set `reversed` on an `{{ef-list ordered=false}}`.

----

All that said - out of curiosity, why is the list `ol`/`ul` aware at all? I.e. what do `reversed`, `start`, and `type` do that isn't possible with a `ul`?

**Comment by notmessenger** [comment]
Per https://html.spec.whatwg.org/multipage/semantics.html#the-ol-element

> reversed — Number the list backwards
start — Ordinal value of the first item
type — Kind of list marker

**Comment by davewasmer** [comment]
Huh, TIL. I obviously don't use `<ol>`'s much :wink:

**Comment by notmessenger** [comment]
lol, yeah it was new to me too :-)

**Comment by notmessenger** [comment]
This conversation is represented in https://github.com/ember-forge/ember-forge-ui/pull/39
