### ISSUE TITLE
Is fs.readdirSync() compatible with multiple versions of Node?

### ISSUE THREAD

**Issue by notmessenger** [ember-forge/ember-forge-ui#5]
In `treeForAddonTemplates()` in *index.js*

It works in version 5.x but what about 6, 4, 0.12, etc?

**Comment by juwara0** [comment]
This call exists in:
0.12 - https://nodejs.org/docs/latest-v0.12.x/api/fs.html#fs_fs_readdirsync_path
4.4.3 - https://nodejs.org/docs/v4.4.3/api/fs.html#fs_fs_readdirsync_path
5.x - https://nodejs.org/docs/latest-v5.x/api/fs.html#fs_fs_readdirsync_path
6.0.0 - https://nodejs.org/docs/v6.0.0/api/fs.html#fs_fs_readdirsync_path_options
