### ISSUE TITLE
Should form element values get updated when their (loosely) bound data object value is updated?

### ISSUE THREAD

**Issue by notmessenger** [ember-forge/ember-forge-ui#70]
*data object*
```
theData: {
  age: 30
}
```

*template*
```
{{#ef-form
  data=theData
  as |f|
}}
  {{f.input-text property="age"}}
{{/ef-form}}
```

*renders this HTML*
`<input type="text" class="ember-view ef-input-text" value="30">`

Should a field which has been associated with a property on the data object that is used to initially populate its value and is the location updated values are written to would also be bound to the property, in that if it changed externally from the form elements it's value in the elements would update?

So in this example, if `theData.age` got updated to `31` from Ember-land code (not via the user entering a new value in the `<input>` element rendered in their browser) should the `value` of the `input` element be changed to reflect the new value of `31`?

**Comment by jagthedrummer** [comment]
I would vote that yes, it should change in the form to match the actual value stored in `theData`.

**Comment by notmessenger** [comment]
@jagthedrummer I was thinking that as well initially but am now thinking that a form should possibly be backed by a proxy (whether actually or just conceptually) in that if I'm filling a form out initially the data being entered is the truth.  If I'm editing existing data then the data is the truth but will the truth be chaining while I'm interacting with the form?  If not, then I don't need to be bound to it.  If so, then how is that managed, as an update from the data to the form would cause the element value to change while you might literally be interacting with it (i.e. typing a sentence).  I'm thinking that a form when rendered has a snapshot of the data and then does an update to the real data.  There are some libraries that do this, can be leveraged, etc.

I'm not even saying that is how we should approach it, but the idea that the data could slide out from under you would be a concern of mine.

**Comment by notmessenger** [comment]
Though I suppose in most cases if a user is on a form route/view/etc they aren't doing other things in the app causing the data to update from underfoot.  This would be only a problem if the application had logic being executed that was doing so.  And if that is the case that is how they architected their application and not a concern of this logic.

If were are to update the form data based on the object the form component is associated/bound to this logic will need to change - https://github.com/ember-forge/ember-forge-ui/blob/form-components/addon/mixins/form/input/common.js#L154-L164

**Comment by jagthedrummer** [comment]
I kinda think that the "data might change underneath you" is more of an application level concern, and not so much a component level concern. I think the component should just know "I'm proxying data to/from this data object" and other than that I don't think it should care much about anything else that might be happening with other actions or updates. Like I said, I kinda think that. I'm open to persuasion.

**Comment by notmessenger** [comment]
I have implemented two-way data binding between the form's data object and the element values

https://github.com/ember-forge/ember-forge-ui/commit/e9b7331152c00a5c3abe6b78d49c8aed3dc6b37f
