### ISSUE TITLE
Where is the truth kept for single use of the form/input/ef-checkbox component?

### ISSUE THREAD

**Issue by notmessenger** [ember-forge/ember-forge-ui#71]
This will be fleshed out more but generally when dealing with a group of checkboxes that are associated with one another (i.e. all things you want to subscribe to) the data object bound to the form will contain a property which is an array of all of the values of any pre-selected values.  Then the template will display all possible options and the intersection between these two datasets will determine whether the `checked` attribute is set on individual checkbox elements.  As the user selects and deselects checkbox elements the inclusion or removal of their `value` from the array property of the data property bound to the form will be managed.

Given that, I have some questions about the use of a single checkbox, such as "check this box to indicate something".

```
{{#ef-form
  data=theData
  as |f|
}}
  {{f.input-checkbox property="isAdmin" value="yes"}}
{{/ef-form}}
```

How do we indicate that this should be pre-selected?

Can definitely do `{{f.input-checkbox property="isAdmin" value="yes" checked=true}}` in the template but then what is the keeper of truth?

From the template perspective only with `{{f.input-checkbox property="isAdmin" value="yes"}}` the `data.isAdmin` property would be empty and the checkbox would be unchecked.  Upon checking it the `data.isAdmin` value would be set to `yes`.  But with `{{f.input-checkbox property="isAdmin" value="yes" checked=true}}` do we treat it the same.  And then when the box is checked (as the default) it then immediately sets `data.isAdmin` to yes?

Or does the `isAdmin` property need to be an array, similar to when there will be groupings of checkboxes) and there needs to be logic like `checked=(if value == "yes")` in the template?  That's verbose but it would follow inline with the approach for multiples and maintain a single source of truth.

DISCLAIMER:  I did not cover all possible scenarios and some of my logic may be a little "sloppy" but hopefully you get the gist of what I'm getting at here and the question(s) I am asking.

**Comment by notmessenger** [comment]
I believe the answer to this question will be influenced by the answer to https://github.com/ember-forge/ember-forge-ui/issues/70 as well

**Comment by notmessenger** [comment]
What I'm currently leaning towards is the following behavior, with each of them stacking on one another, with each being possible and inclusive of the previously-described behavior:

* A checkbox can be used with just the `property` value, and no setting of the `value` or `checked` properties.  When the checkbox is checked the bound property value is set to `on`, per the HTML spec, and `null` when it is unchecked.  This is regardless of whatever value there was in the data object for the `property` value originally.
* A checkbox can be used with the `property` and `value` properties, and no setting of the `checked` property.  When the checkbox is checked the bound property value is set to the value of the `value` property, per the HTML spec, and `null` when it is unchecked.  This is regardless of whatever value there was in the data object for the `property` value originally.
  * If the value of the `property` value equals the value of the `value` property then the `checked` value will automatically be set to `true` by the component.  This includes for initial render and for any updates made to the bound data object (property) after render.
* A checkbox can be used with the `property`, `value`, and `checked` properties.  Regardless of how the comparison between the values of the `property` and `value` properties plays out from the previous behaviors, the setting of the `checked` property to `true` will cause the bound property value to be set to the value of the `value` property, or to `on` if it is not set, per the HTML spec.

**Comment by davewasmer** [comment]
I'm not as familiar with the HTML spec, but speaking from the perspective of a potential Ember dev user of this component:

I would expect a checkbox to simply toggle a Boolean value, with a "nice-to-have" of supporting array membership (but not required). In other words, I would expect just the `property` attribute:

```hbs
{{f.checkbox 'isAdmin'}}
```

I would expect that, when the form initially renders, the checkbox would be checked if `isAdmin` is true, and unchecked if false.

In the array use case, I'd imagine something like this syntax perhaps:

```hbs
{{f.checkbox 'newsletterSubscriptions' value='product'}}
{{f.checkbox 'newsletterSubscriptions' value='marketing'}}
{{f.checkbox 'newsletterSubscriptions' value='security'}}
```

Although that's just off the top of my head.

------

In general, I would avoid the `value` option you mentioned - the use case seems rare, and is easily covered by simply supplying your own computed property getter/setter.

I would also avoid the `checked` option. The semantics are unclear at first glance as to how that interacts with the existing value of the `property` that was supplied. If they differ - does that mean that the component will overwrite `property`? When will that happen (on initialization? didInsertElement? didRender?). I can't imagine a good use case for that functionality.

**Comment by notmessenger** [comment]
Closed by
* https://github.com/ember-forge/ember-forge-ui/commit/a992005e14a643fc21c74c04036f6194458830b2
* https://github.com/ember-forge/ember-forge-ui/commit/fb3012ca2bd38a021c203eaa84a06c14e71dcb1a
* https://github.com/ember-forge/ember-forge-ui/commit/6b2f567de12782d16acd7a20f8c587a66457a773
